// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RailcarTrips.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RailcarTripsProcessingFeature : object, Xunit.IClassFixture<RailcarTripsProcessingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RailcarTripsProcessing.feature"
#line hidden
        
        public RailcarTripsProcessingFeature(RailcarTripsProcessingFeature.FixtureData fixtureData, RailcarTrips_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Railcar trips processing", "  As a user\n  I want to upload railcar/equipment events\n  So that trips are deriv" +
                    "ed, stored, and visible in the UI", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("the city lookup is seeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload and process a valid events file")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Upload and process a valid events file")]
        public void UploadAndProcessAValidEventsFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upload and process a valid events file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table1.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "1"});
                table1.AddRow(new string[] {
                            "CAR1",
                            "Z",
                            "2026-01-02 00:00",
                            "2"});
#line 10
    testRunner.Given("a CSV with events:", ((string)(null)), table1, "Given ");
#line hidden
#line 14
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
    testRunner.Then("1 trips are created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
    testRunner.And("0 errors are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Events are ordered per equipment before processing")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Events are ordered per equipment before processing")]
        public void EventsAreOrderedPerEquipmentBeforeProcessing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Events are ordered per equipment before processing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table2.AddRow(new string[] {
                            "CAR1",
                            "Z",
                            "2026-01-02 00:00",
                            "2"});
                table2.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "1"});
#line 19
    testRunner.Given("a CSV with events:", ((string)(null)), table2, "Given ");
#line hidden
#line 23
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    testRunner.Then("1 trips are created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
    testRunner.And("0 warnings are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Multiple equipment are processed independently")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Multiple equipment are processed independently")]
        public void MultipleEquipmentAreProcessedIndependently()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple equipment are processed independently", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table3.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "1"});
                table3.AddRow(new string[] {
                            "CAR1",
                            "Z",
                            "2026-01-02 00:00",
                            "2"});
                table3.AddRow(new string[] {
                            "CAR2",
                            "W",
                            "2026-01-03 00:00",
                            "1"});
                table3.AddRow(new string[] {
                            "CAR2",
                            "Z",
                            "2026-01-04 00:00",
                            "2"});
#line 28
    testRunner.Given("a CSV with events:", ((string)(null)), table3, "Given ");
#line hidden
#line 34
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
    testRunner.Then("2 trips are created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Missing end event is handled deterministically")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Missing end event is handled deterministically")]
        public void MissingEndEventIsHandledDeterministically()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Missing end event is handled deterministically", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table4.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "1"});
#line 38
    testRunner.Given("a CSV with events:", ((string)(null)), table4, "Given ");
#line hidden
#line 41
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 42
    testRunner.Then("0 trips are created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
    testRunner.And("1 warnings are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Missing start event is handled deterministically")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Missing start event is handled deterministically")]
        public void MissingStartEventIsHandledDeterministically()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Missing start event is handled deterministically", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table5.AddRow(new string[] {
                            "CAR1",
                            "Z",
                            "2026-01-02 00:00",
                            "2"});
#line 46
    testRunner.Given("a CSV with events:", ((string)(null)), table5, "Given ");
#line hidden
#line 49
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
    testRunner.Then("0 trips are created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
    testRunner.And("1 warnings are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Unknown city in events")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Unknown city in events")]
        public void UnknownCityInEvents()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Unknown city in events", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table6.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "99"});
#line 54
    testRunner.Given("a CSV with events:", ((string)(null)), table6, "Given ");
#line hidden
#line 57
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    testRunner.Then("1 errors are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid time workaround")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Invalid time workaround")]
        public void InvalidTimeWorkaround()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid time workaround", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table7.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-03-08 02:30",
                            "3"});
#line 61
    testRunner.Given("a CSV with events:", ((string)(null)), table7, "Given ");
#line hidden
#line 64
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    testRunner.Then("2 warnings are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
    testRunner.And("the stored local time is adjusted to 2026-03-08 03:30", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate input is idempotent")]
        [Xunit.TraitAttribute("FeatureTitle", "Railcar trips processing")]
        [Xunit.TraitAttribute("Description", "Duplicate input is idempotent")]
        public void DuplicateInputIsIdempotent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate input is idempotent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "EquipmentId",
                            "EventCode",
                            "EventTime",
                            "CityId"});
                table8.AddRow(new string[] {
                            "CAR1",
                            "W",
                            "2026-01-01 00:00",
                            "1"});
#line 69
    testRunner.Given("a CSV with events:", ((string)(null)), table8, "Given ");
#line hidden
#line 72
    testRunner.When("I process the CSV", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
    testRunner.And("I process the CSV again", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
    testRunner.Then("2 warnings are reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 75
    testRunner.And("1 stored events exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RailcarTripsProcessingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RailcarTripsProcessingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
